import crossplane
from pprint import pprint

tokens = crossplane.lex('conf/nginx/nginx.conf')
pprint(list(tokens))

"""
[('user', 2, False),
 ('nginx', 2, False),
 (';', 2, False),
 ('worker_processes', 3, False),
 ('auto', 3, False),
 (';', 3, False),
 ('error_log', 5, False),
 ('/var/log/nginx/error.log', 5, False),
 ('notice', 5, False),
 (';', 5, False),
 ('pid', 6, False),
 ('/var/run/nginx.pid', 6, False),
 (';', 6, False),
 ('events', 9, False),
 ('{', 9, False),
 ('worker_connections', 10, False),
 ('1024', 10, False),
 (';', 10, False),
 ('}', 11, False),
 ('http', 15, False),
 ('{', 15, False),
 ('# include       ./mime.types;', 16, False),
 ('default_type', 17, False),
 ('application/octet-stream', 17, False),
 (';', 17, False),
 ('log_format', 19, False),
 ('main', 19, False),
 ('$remote_addr - $remote_user [$time_local] "$request" ', 19, True),
 ('$status $body_bytes_sent "$http_referer" ', 20, True),
 ('"$http_user_agent" "$http_x_forwarded_for"', 21, True),
 (';', 21, False),
 ('access_log', 23, False),
 ('/var/log/nginx/access.log', 23, False),
 ('main', 23, False),
 (';', 23, False),
 ('sendfile', 25, False),
 ('on', 25, False),
 (';', 25, False),
 ('#tcp_nopush     on;', 26, False),
 ('keepalive_timeout', 28, False),
 ('65', 28, False),
 (';', 28, False),
 ('#gzip  on;', 30, False),
 ('ssl_protocols', 32, False),
 ('SSLv3', 32, False),
 ('TLSv1', 32, False),
 (';', 32, False),
 ('ssl_ciphers', 33, False),
 ('ECDHE-ECDSA-AES128-GCM-SHA256', 33, False),
 (';', 33, False),
 ('include', 36, False),
 ('./conf.d/*.conf', 36, False),
 (';', 36, False),
 ('# ssl_protocols SSLv3;', 38, False),
 ('}', 40, False)]
"""